### ISSUE TITLE
Error on almost every page: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by bjohnson-va** [jb55/vimium-plus#5]
```
extensions::uncaught_exception_handler:8Error in event handler for (unknown): TypeError: Cannot read property 'appendChild' of null

    at Object.HUD.createHudElement (chrome-extension://cjfocibepmjhlehihiijgadhgfgnamhp/content_scripts/vimium_frontend.js:1478:20)

    at Object.HUD.displayElement (chrome-extension://cjfocibepmjhlehihiijgadhgfgnamhp/content_scripts/vimium_frontend.js:1469:35)

    at Object.HUD.hide (chrome-extension://cjfocibepmjhlehihiijgadhgfgnamhp/content_scripts/vimium_frontend.js:1491:15)

    at HandlerStack.Mode.push.indicator (chrome-extension://cjfocibepmjhlehihiijgadhgfgnamhp/content_scripts/mode.js:45:23)

    at HandlerStack.bubbleEvent (chrome-extension://cjfocibepmjhlehihiijgadhgfgnamhp/lib/handler_stack.js:40:34)

    at Function.Mode.setIndicator (chrome-extension://cjfocibepmjhlehihiijgadhgfgnamhp/content_scripts/mode.js:189:27)

    at GrabBackFocus.Mode.setIndicator (chrome-extension://cjfocibepmjhlehihiijgadhgfgnamhp/content_scripts/mode.js:185:19)

    at GrabBackFocus.Mode.exit (chrome-extension://cjfocibepmjhlehihiijgadhgfgnamhp/content_scripts/mode.js:226:21)

    at chrome-extension://cjfocibepmjhlehihiijgadhgfgnamhp/content_scripts/vimium_frontend.js:204:26

    at Object.settings.receiveMessage (chrome-extension://cjfocibepmjhlehihiijgadhgfgnamhp/content_scripts/vimium_frontend.js:145:22)

```

Running version 1.50.1

**Comment by jb55** [comment]
This project is actually deprecated now, you can replicate it's functionality with this vimium config:

```
# Insert your preferred key mappings here.
map wo closeOtherTabs
map wH closeTabsOnLeft
map wL closeTabsOnRight
map gF LinkHints.activateModeToOpenInNewForegroundTab
map ' Marks.activateGotoMode
unmap t
```

**Comment by bjohnson-va** [comment]
Oh ok.  Thanks.
